version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: librarydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  library-api:
    build: .
    container_name: library-api
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres-data:
